package com.shop.beans;
// Generated 2016-10-6 15:56:43 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bargain generated by hbm2java
 */
@Entity
@Table(name = "bargain", catalog = "shop")
public class Bargain implements java.io.Serializable {

	private Integer bargainId;
	private Book book;
	private Double boolNewPrice;//Êý¾Ý¿â´íÁË¡£

	public Bargain() {
	}

	public Bargain(Book book) {
		this.book = book;
	}

	public Bargain(Book book, Double boolNewPrice) {
		this.book = book;
		this.boolNewPrice = boolNewPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bargainId", unique = true, nullable = false)
	public Integer getBargainId() {
		return this.bargainId;
	}

	public void setBargainId(Integer bargainId) {
		this.bargainId = bargainId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookId", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@Column(name = "boolNewPrice", precision = 10)
	public Double getBoolNewPrice() {
		return this.boolNewPrice;
	}

	public void setBoolNewPrice(Double boolNewPrice) {
		this.boolNewPrice = boolNewPrice;
	}

}
