package com.shop.beans;
// Generated 2016-10-6 15:56:43 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordersbook generated by hbm2java
 */
@Entity
@Table(name = "ordersbook", catalog = "shop")
public class Ordersbook implements java.io.Serializable {

	private Integer ordersbookId;
	private Book book;
	private Orders orders;
	private int bookAmount;

	public Ordersbook() {
	}

	public Ordersbook(Book book, Orders orders, int bookAmount) {
		this.book = book;
		this.orders = orders;
		this.bookAmount = bookAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ordersbookId", unique = true, nullable = false)
	public Integer getOrdersbookId() {
		return this.ordersbookId;
	}

	public void setOrdersbookId(Integer ordersbookId) {
		this.ordersbookId = ordersbookId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookId", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordersId", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "bookAmount", nullable = false)
	public int getBookAmount() {
		return this.bookAmount;
	}

	public void setBookAmount(int bookAmount) {
		this.bookAmount = bookAmount;
	}

}
